# Generated by Django 3.0.6 on 2023-10-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unstop', '0004_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_seat_count',
            new_name='last_booked_seat_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remaining_seats',
        ),
    ]
